nservices:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - ecommerce
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://kafka:9090,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9090,EXTERNAL://185.110.189.239:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - ecommerce
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=user
      - POSTGRES_DB=ecommerce
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    hostname: db
    networks:
      - ecommerce
  
  order:
    build: ./order
    restart: always
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    networks:
      - ecommerce
    ports:
      - '3001:3001'    
  inventory:
    build: ./inventory
    restart: always
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    networks:
      - ecommerce
    ports:
      - '3002:3001'    
  
    

  product:
    build: ./product
    restart: always
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    networks:
      - ecommerce
    ports:
      - '3003:3001'  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - ecommerce
networks:
  ecommerce:
    driver: bridge

